# Takenlijst voor het configureren van de webserver

# Installeer Apache
- name: Install Apache
  apt:
    name: apache2
    state: present

# Installeer PHP
- name: Install PHP
  apt:
    name: php
    state: present

# Zorg ervoor dat Apache actief is en ingeschakeld
- name: Ensure Apache is running and enabled
  service:
    name: apache2
    state: started
    enabled: yes

# Installeer de PHP MySQLi-extensie
- name: Install PHP MySQLi extension
  apt:
    name: php-mysqli
    state: present

# Kopieer index.php naar de webserver
- name: Copy index.php to webserver
  template:
    src: index.php.j2
    dest: /var/www/html/index.php
  notify:
    - restart apache
