# Takenlijst voor het configureren van de load balancer

# Installeer HAProxy
- name: Install HAProxy
  apt:
    name: haproxy
    state: present

# Configureer HAProxy
- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy
